import "./globals.css";
import 'react-photo-view/dist/react-photo-view.css';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigProvider } from 'antd';
import locale from 'antd/locale/id_ID';
import QueryProvider from "@/components/query_provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id-ID">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConfigProvider locale={locale}>
          <QueryProvider>
            {children}
          </QueryProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
